//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationServiceStagiaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tuteur
    {
        public Tuteur()
        {
            this.Stagiaire = new HashSet<Stagiaire>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Adresse { get; set; }
        public Nullable<int> CodePostal { get; set; }
        public Nullable<int> Telephone { get; set; }
    
        public virtual ICollection<Stagiaire> Stagiaire { get; set; }
    }
}
